

FROM node:22-alpine AS node

WORKDIR /app

ARG VITE_APP_NAME=SocialNetwork
ARG VITE_REVERB_HOST=localhost
ARG VITE_REVERB_PORT=6001
ARG VITE_REVERB_SCHEME=http

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_REVERB_HOST=$VITE_REVERB_HOST
ENV VITE_REVERB_PORT=$VITE_REVERB_PORT
ENV VITE_REVERB_SCHEME=$VITE_REVERB_SCHEME

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
COPY laravel-app.conf /etc/nginx/laravel-app.conf
COPY .htpasswd /etc/nginx/.htpasswd
COPY ssl/ /etc/nginx/ssl/

COPY --from=node /app/public /var/www/html/public

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
