services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ENDPOINT=http://storage:9000
      - REVERB_HOST=reverb
      - REVERB_PORT=8080
      - PUSHER_HOST=reverb
      - PUSHER_PORT=8080
    depends_on:
      redis:
        condition: service_started
      reverb:
        condition: service_started
      storage:
        condition: service_started
    networks:
      - app-network

  reverb:
    image: php:8.2-cli
    container_name: laravel_reverb
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan reverb:start
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: laravel_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/tmp/nginx.conf:ro
    depends_on:
      - php
    networks:
      - app-network
  storage:
    image: minio/minio
    container_name: minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minio124
      MINIO_ROOT_PASSWORD: minio1235
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ministorage_data:/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ministorage_data:
